### ISSUE TITLE
[FusionForge] v0.8.0 error when loading in game 0.10.29.21950

### ISSUE THREAD

**Issue by starfi5h** [James-Fire/DSP-Mods#1]
```ini
An error has occurred! Game version 0.10.29.21950
6 Mods used: [ErrorAnalyzer1.1.0] [IlLine1.0.0] [DSP Mod Save1.2.1] [LDBTool3.0.1] [DSP Common API1.6.4.0] [FusionForge Plug-In1.1.0.0] 
NullReferenceException: Object reference not set to an instance of an object
FusionForge.FusionForge.Awake ();(IL_0EAC)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Application:.cctor()
XLogHandler:Register()
GlobalObject:Initialize()
```

**Comment by James-Fire** [comment]
I get that in the console too, but it doesn't appear to actually cause any issues? All the recipes are there, and you can use them fine.

So I'm not sure what the actual issue is, or how to fix it. And since it appears to not cause any problems...

**Comment by starfi5h** [comment]
This line where adding recipes to itemProto gets error
https://github.com/James-Fire/DSP-Mods/blob/main/Fusion%20Forge/Fusion%20Forge/Class1.cs#L224C22-L224C29
So the itemTip doesn't show the new recipes added by the mod
![image](https://github.com/user-attachments/assets/829272e0-57ab-40c4-ac21-e7d05bfc6f99)

**Comment by James-Fire** [comment]
> This line where adding recipes to itemProto gets error https://github.com/James-Fire/DSP-Mods/blob/main/Fusion%20Forge/Fusion%20Forge/Class1.cs#L224C22-L224C29 So the itemTip doesn't show the new recipes added by the mod ![image](https://private-user-images.githubusercontent.com/50672801/367757789-829272e0-57ab-40c4-ac21-e7d05bfc6f99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1MTE1OTIsIm5iZiI6MTcyNjUxMTI5MiwicGF0aCI6Ii81MDY3MjgwMS8zNjc3NTc3ODktODI5MjcyZTAtNTdhYi00MGM0LWFjMjEtZTdkMDViZmM2Zjk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE2VDE4MjgxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzODdjMWQyYjQ3NjAzODEzMGEyNjBkOGIxZTcxZWFhNzIxNjczZmY4NTVmNGEyYmY0MDdlZGI4MDJlMThmMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UTipMWW9PXcBH-p_GJokxZEiLdw0CH29acuwEjhpVCw)

Oh okay

When did that change? And what did it change to? If you know either of those

**Comment by starfi5h** [comment]
`ItemProto.recipes` is initialized in `ItemProto.FindRecipes()`, which is not ready yet in Awake.
so you need to hook the actions to modify `ItemProto.recipes` in the later stage of the game. For example, [hook on `LDBTool.PostAddDataAction`](https://github.com/limoka/CommonAPI/blob/master/CommonAPI/Systems/ProtoRegistrySystem/ProtoRegistry.cs#L85).
